#!/usr/bin/env python3
"""LinkedIn auto-connect via Playwright over CDP — using preload custom-invite URL.

Reference / fixed-list version. For the supported daily-batch workflow, use
``scripts/send_daily.py``, which reads targets from ``~/.linkedin-outreach/queue.jsonl``
generated by ``scripts/find_leads.py`` and tracks daily caps in ``sent.jsonl``.

Drop your own list into ``TARGETS`` if you want a one-off run that does not depend
on the queue file. Each item: {company, name, url, note}.
"""
import asyncio
import datetime
import json
import random
from pathlib import Path
from urllib.parse import urlparse

from playwright.async_api import async_playwright, TimeoutError as PWTimeout

CDP_URL = "http://127.0.0.1:9222"
LOG_DIR = Path.home() / ".linkedin-outreach" / "runs"
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_PATH = LOG_DIR / f"cdp_run_{datetime.datetime.now():%Y%m%d_%H%M%S}.json"

# Example shape — fill in with your own targets, or use send_daily.py instead.
TARGETS: list[dict] = [
    # {
    #   "company": "Example Inc",
    #   "name":    "Jane Doe",
    #   "url":     "https://www.linkedin.com/in/jane-doe-xxxx/",
    #   "note":    "Hi Jane, I came across Example Inc and your role. I'd like to connect.",
    # },
]


def vanity_name(profile_url: str) -> str:
    path = urlparse(profile_url).path
    parts = [p for p in path.split("/") if p]
    if len(parts) >= 2 and parts[0] == "in":
        return parts[1]
    return ""


async def find_invite_dialog(page, timeout_ms=12000):
    deadline = asyncio.get_event_loop().time() + timeout_ms / 1000
    while asyncio.get_event_loop().time() < deadline:
        ok = await page.evaluate(
            """
            () => {
              const isVis = el => { const r = el.getBoundingClientRect(); return r.width > 0 && r.height > 0; };
              const dialogs = Array.from(document.querySelectorAll('div[role="dialog"]')).filter(isVis);
              return dialogs.some(d => /add a note to your invitation|how do you know|invitation limit|you have unlimited notes/i.test(d.innerText || ''));
            }
            """
        )
        if ok:
            return True
        await asyncio.sleep(0.4)
    return False


async def send_one(page, target):
    vanity = vanity_name(target["url"])
    if not vanity:
        return {"status": "skip", "reason": "bad_url"}
    invite_url = f"https://www.linkedin.com/preload/custom-invite/?vanityName={vanity}"

    await page.goto(invite_url, wait_until="domcontentloaded", timeout=30000)
    await asyncio.sleep(5)

    if not await find_invite_dialog(page):
        page_text = (await page.evaluate("() => document.body.innerText || ''")).lower()
        if "pending" in page_text and "invitation" in page_text:
            return {"status": "skip", "reason": "already_pending"}
        return {"status": "skip", "reason": "no_invite_dialog"}

    dialog_text = (await page.evaluate(
        '''() => {
          const isVis = el => { const r = el.getBoundingClientRect(); return r.width > 0 && r.height > 0; };
          const d = Array.from(document.querySelectorAll('div[role="dialog"]')).filter(isVis).find(x => /add a note to your invitation|how do you know|invitation limit/i.test(x.innerText||''));
          return d ? (d.innerText||'').toLowerCase() : '';
        }'''
    )) or ""

    if "how do you know" in dialog_text:
        await page.keyboard.press("Escape")
        return {"status": "skip", "reason": "requires_email"}
    if "invitation limit" in dialog_text:
        await page.keyboard.press("Escape")
        return {"status": "skip", "reason": "weekly_limit"}

    add_note = page.locator('div[role="dialog"] button:has-text("Add a note")').first
    note_added = False
    try:
        await add_note.click(timeout=5000)
        await asyncio.sleep(1.2)
        ta = page.locator('div[role="dialog"] textarea').first
        await ta.fill(target["note"][:200], timeout=5000)
        note_added = True
        await asyncio.sleep(0.6)
    except Exception as e:
        return {"status": "skip", "reason": f"note_failed: {type(e).__name__}"}

    send_btn = None
    for sel in [
        'div[role="dialog"] button[aria-label="Send invitation"]',
        'div[role="dialog"] button[aria-label="Send now"]',
        'div[role="dialog"] button:has-text("Send invitation")',
        'div[role="dialog"] button:has-text("Send")',
    ]:
        loc = page.locator(sel).first
        if await loc.count() > 0:
            send_btn = loc
            break
    if not send_btn:
        return {"status": "skip", "reason": "send_button_not_found"}
    try:
        await send_btn.click(timeout=5000)
    except Exception as e:
        return {"status": "skip", "reason": f"send_click_failed: {type(e).__name__}"}

    await asyncio.sleep(2.5)
    return {"status": "sent", "note_added": note_added}


async def main():
    if not TARGETS:
        print("TARGETS is empty — fill it in, or use scripts/send_daily.py with the queue.jsonl workflow.")
        return
    log = []
    async with async_playwright() as pw:
        browser = await pw.chromium.connect_over_cdp(CDP_URL)
        ctx = browser.contexts[0]
        page = next((p for p in ctx.pages if "linkedin.com" in (p.url or "")), None)
        if page is None:
            page = await ctx.new_page()
            await page.goto("https://www.linkedin.com/feed/")
        await page.bring_to_front()

        for i, t in enumerate(TARGETS, 1):
            print(f"[{i}/{len(TARGETS)}] {t['name']} - {t['company']}")
            try:
                result = await send_one(page, t)
            except Exception as e:
                result = {"status": "error", "reason": f"{type(e).__name__}: {e}"}
            record = {
                "idx": i, "company": t["company"], "name": t["name"],
                "url": t["url"], "note": t["note"], "result": result,
                "ts": datetime.datetime.now().isoformat(timespec="seconds"),
            }
            log.append(record)
            LOG_PATH.write_text(json.dumps(log, ensure_ascii=False, indent=2))
            print("   ->", result)
            if i < len(TARGETS):
                pause = random.randint(35, 60)
                print(f"   sleep {pause}s")
                await asyncio.sleep(pause)
        await browser.close()
    print("DONE", LOG_PATH)


if __name__ == "__main__":
    asyncio.run(main())
